simpson_acceuil:
    path:     /
    defaults: { _controller: OCPlatformBundle:Simpson:affiche }	
ajoute_citation:
    path:     /citations/ajout
    defaults: { _controller: OCPlatformBundle:Quote:fillQuote }
affiche_citation:
    path:     /citations/affiche
    defaults: { _controller: OCPlatformBundle:Quote:showQuote }
affiche_quote:
    path:     /citations
    defaults: { _controller: OCPlatformBundle:Quote:quote }
supprim_citation: 
    path:     /citations/supprim/{id}
    defaults: { _controller: OCPlatformBundle:Quote:supprimer}
ajoute_perso:
    path:     /personnages/ajout
    defaults: { _controller: OCPlatformBundle:Perso:fillPerso }
affiche_perso:
    path:     /personnages/affiche
    defaults: { _controller: OCPlatformBundle:Perso:showPerso }
article_perso:
    path:     /personnages/article/{id}
    defaults: { _controller: OCPlatformBundle:Perso:perso }
acceuil_perso:
    path:     /personnages
    defaults: { _controller: OCPlatformBundle:Perso:acceuilPerso }
affiche_perso_list: 
    path:     /personnages/liste/{numero}
    defaults: { _controller: OCPlatformBundle:Perso:persoList}
formulaire_modif: 
    path:     /personnages/modif/{id}
    defaults: { _controller: OCPlatformBundle:Perso:initModifPerso}
enregistre_modif: 
    path:     /personnages/enregistre/{id}
    defaults: { _controller: OCPlatformBundle:Perso:modifPerso}
supprim_perso: 
    path:     /personnage/supprim/{id}
    defaults: { _controller: OCPlatformBundle:Perso:supprimer}
ajoute_saison:
    path:     /saisons/ajout
    defaults: { _controller: OCPlatformBundle:Saison:fillSaison }
affiche_saison:
    path:     /saisons/affiche
    defaults: { _controller: OCPlatformBundle:Saison:showSaison }
article_saison:
    path:     /saison/episode/{id}
    defaults: { _controller: OCPlatformBundle:Saison:saison }
acceuil_saison:
    path:     /saisons
    defaults: { _controller: OCPlatformBundle:Saison:acceuilSaison }
affiche_saison_num: 
    path:     /saison/{numero}
    defaults: { _controller: OCPlatformBundle:Saison:saisonX}
formulaire_modif_saison: 
    path:     /saisons/modif/{id}
    defaults: { _controller: OCPlatformBundle:Saison:initModifsaison}
enregistre_modif_saison: 
    path:     /saisons/enregistre/{id}
    defaults: { _controller: OCPlatformBundle:Saison:modifSaison}
supprim_saison: 
    path:     /saisons/supprim/{id}
    defaults: { _controller: OCPlatformBundle:Saison:supprimer}
saviez-vous_form:
    path:     /saviez-vous/formulaire
    defaults: { _controller: OCPlatformBundle:SaviezVous:formulaire }
saviez-vous_ajout:
    path:     /saviez-vous/article
    defaults: { _controller: OCPlatformBundle:SaviezVous:ajout }
saviez-vous_article:
    path:     /saviez-vous/article/{id}
    defaults: { _controller: OCPlatformBundle:SaviezVous:article }
saviez-vous_form_modif:
    path:     /saviez-vous/modif/{id}
    defaults: { _controller: OCPlatformBundle:SaviezVous:InitModifier }
saviez-vous_modif:
    path:     /saviez-vous/article/modif/{id}
    defaults: { _controller: OCPlatformBundle:SaviezVous:Modifier }
saviez-vous_supp:
    path:     /saviez-vous/article/supp/{id}
    defaults: { _controller: OCPlatformBundle:SaviezVous:supprimer }
saviez-vous_list:
    path:     /saviez-vous/liste
    defaults: { _controller: OCPlatformBundle:SaviezVous:afficheList }
goodies_form:
    path:     /goodies/formulaire
    defaults: { _controller: OCPlatformBundle:Goodies:formulaire }
goodies_ajout:
    path:     /goodies/article
    defaults: { _controller: OCPlatformBundle:Goodies:ajout }
goodies_article:
    path:     /goodies/article/{id}
    defaults: { _controller: OCPlatformBundle:Goodies:article }
goodies_form_modif:
    path:     /goodies/modif/{id}
    defaults: { _controller: OCPlatformBundle:Goodies:InitModifier }
goodies_modif:
    path:     /goodies/article/modif/{id}
    defaults: { _controller: OCPlatformBundle:Goodies:Modifier }
goodies_supp:
    path:     /goodies/article/supp/{id}
    defaults: { _controller: OCPlatformBundle:Goodies:supprimer }
goodies_list:
    path:     /goodies/liste
    defaults: { _controller: OCPlatformBundle:Goodies:afficheList }
serie_article:
    path:     /serie
    defaults: { _controller: OCPlatformBundle:Serie:article }
serie_form_modif:
    path:     /serie/modif
    defaults: { _controller: OCPlatformBundle:Serie:InitModifier }
serie_modif:
    path:     /serie/article/modif
    defaults: { _controller: OCPlatformBundle:Serie:Modifier }
